### ISSUE TITLE
Dataset mismatch

### ISSUE THREAD

**Issue by antonio-mastropaolo** [ds4an/CoDas4CG#2]
Hi all

I just downloaded your dataset, and what I found is confusing me.
Let's pick the folder name "527D" which belongs to the dataset2.zip file.
If I open the folder, I can see the following subfolders: c, cpp, java, python.
If open the file 10350773.py and 10350773.c there is the same code in both of them. I was expecting c code in the c file and python code in the other one. Apparently, we only have python code. 
Moreover,  if I open the file 10373529.cpp I find java code instead of c++.
Can you explain to me how to retrieve for a given task at hand the implementation in multiple languages?

Thank you in advance :)

**Comment by sakura182** [comment]
We checked the dataset again. It may be that there is an error in the text writing script, which caused the current data set language doping. We decided to recheck and upload it. In the 527D, the files in the c language and c++ language are included. It can be opened for inspection. You can use the content under the python language folder. This part has been manually checked to ensure that there are no errors. After that, we will upload a new version of the multilingual data set for your use.

**Comment by sakura182** [comment]
> Hi all
> 
> I just downloaded your dataset, and what I found is confusing me.
> Let's pick the folder name "527D" which belongs to the dataset2.zip file.
> If I open the folder, I can see the following subfolders: c, cpp, java, python.
> If open the file 10350773.py and 10350773.c there is the same code in both of them. I was expecting c code in the c file and python code in the other one. Apparently, we only have python code.
> Moreover, if I open the file 10373529.cpp I find java code instead of c++.
> Can you explain to me how to retrieve for a given task at hand the implementation in multiple languages?
> 
> Thank you in advance :)



> Hi all
> 
> I just downloaded your dataset, and what I found is confusing me.
> Let's pick the folder name "527D" which belongs to the dataset2.zip file.
> If I open the folder, I can see the following subfolders: c, cpp, java, python.
> If open the file 10350773.py and 10350773.c there is the same code in both of them. I was expecting c code in the c file and python code in the other one. Apparently, we only have python code.
> Moreover, if I open the file 10373529.cpp I find java code instead of c++.
> Can you explain to me how to retrieve for a given task at hand the implementation in multiple languages?
> 
> Thank you in advance :)

We checked the dataset again. It may be that there is an error in the text writing script, which caused the current data set language doping. We decided to recheck and upload it. In the 527D, the files in the c language and c++ language are included. It can be opened for inspection. You can use the content under the python language folder. This part has been manually checked to ensure that there are no errors. After that, we will upload a new version of the multilingual data set for your use.

**Comment by sakura182** [comment]
We checked the dataset again. It may be that there is an error in the text writing script, which caused the current data set language doping. We decided to recheck and upload it. In the 527D, the files in the c language and c++ language are included. It can be opened for inspection. You can use the content under the python language folder（The content contained in the sql file）. This part has been manually checked to ensure that there are no errors. After that, we will upload a new version of the multilingual dataset for your use.

**Comment by antonio-mastropaolo** [comment]
Hi @sakura182 do you have any news about the new version?

**Comment by sakura182** [comment]
Hello, sorry to keep you waiting. We will upload a new version for you in a week

**Comment by sakura182** [comment]
Hi,@antonio-mastropaolo , we updated the new dataset, you can use now.
