### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../data//map.pkl'

### ISSUE THREAD

**Issue by vqingtianv** [ds4an/CoDas4CG#3]
I tried to run 'main.py' from "\CodeOfApproaches\seq2seq\seq2seq\atis\lstm\main.py". But it showed “FileNotFoundError: [Errno 2] No such file or directory: '../data//map.pkl' ”. How do I get 'map.pkl'?

**Comment by sakura182** [comment]
hi,vqingtianv:
In our paper, we only used the train file on ac2/attention3, and not atis. If you have problem about it, we recommend you to ask the original author of the tool, the  link address can be found in the seq2seq reference in this paper. Or you can use it,
http://aclweb.org/anthology/P/P16/P16-1004.pdf

**Comment by sakura182** [comment]
hi,vqingtianv:
In our paper, we only used the train file on ac2/attention3, and not atis. If you have problem about it, we recommend you to ask the original author of the tool, the link address can be found in the seq2seq reference in this paper. Or you can use it,
http://aclweb.org/anthology/P/P16/P16-1004.pdf

**Comment by vqingtianv** [comment]
Thank you for your reply very much!
I'm just starting to learn how to use machine learning to generate code. I'd like to ask you a question. For many lines of long code is generated by line, and then combined?

**Comment by sakura182** [comment]
The principles of different code generation methods are different. There are cases like what you said, and there are cases where ast trees are generated and then converted into code form. That kind of code is not generated according to lines.

**Comment by vqingtianv** [comment]
I just tried to run 'main.py' from "\CoDas4CG-master\CodeOfApproaches\seq2seq\seq2seq\ac2\attention3\main.py". But it still showed “FileNotFoundError: [Errno 2] No such file or directory: '../data//map.pkl' ”. Could you provide me with ‘map.pkl’ ？

**Comment by vqingtianv** [comment]
Recently, I tried to run code that generates code by line. I found that this generation is only generated by line and does not include indentation. For example, C + + code does not generate '{' or '}' completely. In synthesis, a certain real value is needed to guide the generation of the corresponding '{' or '}'. At present, this method is not completely end-to-end generation, need some real indentation and '{}' information to guide the generation of the final code?
Looking forward to your reply again. You can also reply to me by email. My email is qianqyu@mail.ustc.edu.cn or yu__qian_qian@163.com.

**Comment by sakura182** [comment]
The file has been sent to your mailbox. You can try this method. The code files we tested are mostly python files, which do not contain {}, but the indentation needs to be included. The specific steps need to be verified by your own experiments.
